import Footer from './Footer';
import Navbar from './Navbar';
import Head from 'next/head'

export default function Layout ({ children }) {
  return (
    <div >
      <Head>
        <title>Club Noir</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header>
        <Navbar />
      </header>
      
      <main>{children}</main>

      <footer>
        <Footer />
      </footer>
      
    </div>
  );
}